# Graduate students {#training-grad-students}

Graduate school is designed to help make you a more independent scientist. In the QMEL, graduate students are expected to co-develop their projects with the lab PI as opposed to being handed a specific project. This freedom can be GREAT, but it can also make you feel adrift at times. That is okay and it is expected. Especially early in graduate school, you should be spending a significant portion of your time reading, taking classes, attending talks, and meeting others. The goal is to think broadly and come up with interesting questions.

The goal of graduate school is not to get a degree. The goal is to learn how to think critically, learn skills, and to get the job you want after graduation. My goal as an advisor is to help you accomplish these things. Early and often communication is key to a strong advisor-advisee relationship. I have to know when you need help in order for me to be a good advisor.

During your time as a grad student in the QEML, you will have several responsibilities:

1.  Taking care of yourself
2.  Taking classes
3.  Attending conferences and giving presentations
4.  Working on projects/papers related to your thesis
5.  Working on projects/papers not related to your thesis
6.  Serving as a teaching assistant or teaching courses
7.  Mentoring students
8.  Applying for funding and fellowships
9.  Applying for jobs
10. Science communication and outreach
11. Staying up to date on the latest science

There is clearly a lot to being a graduate student. It can sometimes be difficult to know where to spend your time, which is your most precious resource. I use the term backwards design (which I’ve stolen from research on pedagogy) to overcome this problem. The key is to think about where you want to be after graduate school. Do you want to be a professor? Then it will be important to publish, get funding, and teach courses in graduate school. Do you want to work on science policy? Then it will be important to publish, work with local officials, and apply for opportunities related to policy. Meetings with Easton and others in the lab or on campus will help clarify some of these choices.

In order to be successful as a scientist, it is critical that you stay up to date on the latest research. This can be a formidable challenge but it can be facilitated by using RSS feeds or emails with journal table of contents. Setting up Google Scholar alerts can also be helpful for specific key words. You can also consider following scientists or scientific organizations on Twitter.

## Committees


### Easton on non-QMEL student committees

Given ongoing commitments, for 2025-2026, I am unlikely to join any student committees. 

Thank you for considering me as part of your graduate student committee. I am honored. A graduate committee membership is a role I take very seriously. I have served on graduate committees in biology, natural resources, oceanography, applied math, and for students outside of my institution. 

Largely because of my role in teaching a graduate-level Data Science course (BIOL 806), I often receive requests to join committees because of my R expertise. Unfortunately, for me to join a committee, this is not enough of a justification. I receive 10+ graduate committee requests per year and, regrettably, I must turn down many requests. 

As you consider me for your committee, please review my specific areas of expertise ([https://quantmarineecolab.github.io/](https://quantmarineecolab.github.io/)) and consider what expertise I would bring to your project. 

Potential reasons I may join a committee:

-	Project related to extreme events, how to improve ecological monitoring, or socio-ecological dynamics
-	Project involving quantitative biology education or outreach
-	Project pertaining to one of my existing study systems: Great Bay, Madagascar, Eastern Tropical Pacific
-	Project with specific analysis needs such as population modeling, time series analysis, simulation approaches
-	Another extraordinary or compelling situation (there are always exceptions)


## Academics

Specific requirements of MS and PhD students depend on whether they are enrolled in Marine Biology or Integrative Bioloy. These requirements are updated more regularly in [internal departmental documents](https://universitysystemnh.sharepoint.com/teams/UNHDBS/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUNHDBS%2FShared%20Documents%2FGraduate%20Students&viewid=4c4a5c2a%2D829f%2D4549%2Db195%2D31d0fb25b563). The goal here is lay out requirements, coursework, and timelines more specific to QMEL. There are also details about requirements at the [Graduate School level available](https://catalog.unh.edu/graduate/academic-regulations-degree-requirements/degree-requirements/#text).

Learning outcomes of a graduate degree from QMEL

### Official Program Learning Outcomes (across MS/PhD and MB/IB) 


By the time of graduation,  

Students will demonstrate expertise in quantitative skills including (a) basic math and statistics; (b) spreadsheet software; (c) graphical presentation of quantitative data. 

Students will demonstrate writing skills that enable them to prepare a scientific research paper in standard format for their field. 

Students will demonstrate competency in experimental design, including the ability to articulate a testable hypothesis and design an appropriate experiment to test it. 

Students will demonstrate communication skills including the ability to clearly explain scientific information to both professional and general audiences. 

Students will demonstrate broad understanding of fundamental areas of biology, especially areas relevant to their research project. 
 

In addition to the above learning outcomes, we have some more detailed requirements for those graduating from QMEL.  



QMEL Learning Outcomes 

 

An understanding of linear models, including GLMs, fixed versus random effects, residuals analyses, model interpretations 

The use of Rmarkdown/Quarto for producing reproducible documents 

Building clean code and documentation 

MS students must submit a manuscript to a peer-reviewed journal by the time they graduate and PhD students must have at least one paper accepted by graduation 

All students will present at a national/international conference in addition to presenting at UNH venues 

All students must apply for at least one (on average) grant/fellowship per year (even if you already have funding for your work) 

Students will know the key modern and historical literature relevant to their research project 

Even if a data-driven or theoretical project, students will know the details of their species or study system inside out 

All students should participate in some field work even if not the primary goal of their project 

 

For PhD students considering academic careers, you should also participate in professional development activities relating to teaching (such as the Grad Cert in College Teaching, https://www.unh.edu/professional-success/ceitl/graduate-certificate-college-teaching) and be the instructor for a course. We usually have to be creative with how to get you to be the instructor for a course as it isn’t a common practice within our department.  

 

In addition to courses and the thesis/dissertation, the requirements for graduation from the lab are as follows: 

MS:  

Passing: 1 manuscript in preparation for submission  

Excel: 1 manuscript submitted, 1 in preparation for submission 

PhD:  

Passing: 2 submitted, a third possible  

Excel: 1 published, 1 submitted, 1-2 that are possible 

 

Key competencies

1. 
2. 

### Course Registration

Minimum number of credits 

For graduate students the minimum semester requirement is 9 credits (6 credits if on a full assistantship) or registration for Master's Thesis (BIOL 899) or Doctoral Research (BIOL 999). For students after their first year, they will likely take just the 899 or 999, which are technically 0 credits, but ensure you are full-time. 

Most of the information on this page is taken from https://catalog.unh.edu/graduate/general-information/registration/ 

#### MS students 

MS students need 30 credits to graduate. This is a mix of real courses, BIOL 895, and BIOL 899. If you are on a TA-ship, you should take 12 credits per semester. If you are on an RA-ship, we have to be more careful about how many classes you register for (it is more expensive for Easton if you are on an RA-ship). 

If you TA in Fall and Spring, you can take J-term courses for free. You can take a real course or BIOL 895. You should be doing one or the either if this situation fits you, especially in year 1 of your MS. You can also take GRAD-listed courses (e.g., teaching workshops) in summer. 

The “typical” MS student should complete all 30 credits (12 Fall, 4 J-term, 12 Spring, 2 Summer) if they are on TA-ship in year 1. Thus, we won’t have to pay for tuition during year 2. Once completed with courses, MS students simply register for BIOL 800 which gives them full time status without having to pay tuition. 

Note that Master’s students are capped at 10 total credits of BIOL 899. If you need extra credits, you can enroll in GRAD 900 but to do that you need to contact the grad school. In general, “spend” your BIOL 899 credits wisely and consider how your courses are distributed across semesters to ease your coursework burden. 

#### PhD Students 

There are no credit requirements for PhD students. However, both the IB and MB degrees have course requirements (please see DBS documentation for details: https://colsa.unh.edu/biological-sciences/key-documents). The course “requirements” are a bit loose, and students can often petition out of the requirements. If you are on a TA-ship (and some specific RA-ships) your tuition is covered by the university. Thus, you are encouraged to take most of your coursework during these semesters. When you are not taking coursework, and especially after your qualifying exam, you can simply sign up for BIOL 999. It is a zero-credit course, but it ensures you are full-time and retain your student benefits. If is a LOT cheaper for students to take BIOL 999 ($1000 per semester) as opposed to other credits ($8000 per semester at least). If you are on an RA that Easton is paying for, it is best to not sign up for a lot of courses, but you should discuss with him further.  

 

### MS program

#### MS proposal

#### MS defense

Students typically defend their MS about one month from the end of the term in which they plan to graduate (e.g., a defense in early April if trying to graduate in May). The graduate school actually requires this earlier defense date. Students then typically have about a month to address any comments that come out of the defense. 

One of the most exciting and nerve-wracking times of a graduate program is your defense day. The day is a mix of celebration and often difficult discussions. 

Scheduling your defense: 4-6 weeks before the defense

The day of the defense: Be sure to show up to the room early to test equipment and to get situated. Despite you wanting to focus on the defense itself, everyone who enters the room will want to say something to you to show their support. Easton will speak for a few minutes to introduce you and the plan for the day. You will then have 30-40 minutes to present your work. Your presentation will then be followed by 10-20 minutes of questions. 

There will be a weird mix of emotions after the hour-long public defense. Friends and family will congratulate you. You should spend time soaking it in. You have successfully passed ½ of the defense. You’ll have a moment to breath or go to the restroom before transitioning to the private defense (usually in a separate, smaller room). 

In the private defense, Easton will explain the format and plan for the private defense. The defense will start with each committee member asking a few questions (10-15 minutes) before the next committee member starts. Once every committee member has had a chance to ask questions, we will open the discussion for anyone to ask additional questions. Easton will take notes to let you focus on answering questions. 

After about 30-90 minutes of questions and discussion, the committee will ask that you leave the room. Walk down the hall, take a breath, but don’t go too far. We will come get you after 5-10 minutes of discussion. You will then join the committee and Easton will share the consensus decision of the whole group. There are three options. 

1.	Fail (extremely unlikely as Easton wouldn’t let you defend if he thought this was a possibility)
2.	Need major revisions before passing (the most common option)
3.	Pass with minor revisions (it happens, but isn’t super common)

If the consensus is number (2) above (which is the most likely), Easton and the committee will provide a blueprint for what needs to happen before they can sign up on your thesis/dissertation. 

You should take a moment to collect your thoughts, write down any notes, and breath. Usually, you and Easton will have a minute to chat. The goal is to wrap up the thoughts for the day and take a break. Once you have captured any important ideas, put your thesis and notes away. In a few days, return to the notes. You and Easton will make a plan at this point to finish and address committee concerns. In the meantime, spend time with family and friends, eat, sleep, relax, etc. You need a break after a day full of emotion. 




### PhD program

Responsible Conduct of Research

As a land-­grant institution, the University of New Hampshire (UNH) is accountable to New Hampshire residents and to the University community to ensure the ethical and safe conduct of research and scholarly activity. As an institution of higher education that prides itself on extensive research endeavors and the involvement of undergraduates and graduate students in research projects, UNH has an obligation to teach and actively promote integrity in research and scholarship.

To fulfill its obligations, UNH has embarked on a program on the responsible conduct of [research and scholarly activity (RCR)](http://www.unh.edu/research/responsible-conduct-research-scholarly-activity) to:

- Raise the consciousness of faculty, staff, and students regarding the ethical and responsible conduct of research and scholarly activity;
- Establish a knowledge base that defines normative and/or professional behavior to assist faculty, staff, and students in making ethical and responsible decisions in the conduct of research and scholarly activity; and
- Foster an institutional culture of integrity in research and scholarly activity.

To support these efforts, the Graduate Council has mandated that all incoming Ph.D. students complete RCR training approved by the Graduate School by the end of their first semester. For more information, [visit the RCR website](http://www.unh.edu/research/responsible-conduct-research-scholarly-activity).

#### PhD proposal

At the end of year one or early in year 2 (by the end of year 2 at the latest), you are expected to formally defend your PhD proposal. The proposal is an opportunity to formalize your PhD plan and receive feedback from the committee. Your PhD path will surely change along the way, so the proposal is exactly that---a proposal. Proposals in QMEL tend to be more detailed than those in other labs. In particular, we write propoosals in "manuscript format" where each chapter is described with an introduction and methods section. 

There is some information on the PhD proposal [available here for current students](https://universitysystemnh.sharepoint.com/teams/UNHDBS/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUNHDBS%2FShared%20Documents%2FGraduate%20Students%2FMB%20Program%20Documents&viewid=4c4a5c2a%2D829f%2D4549%2Db195%2D31d0fb25b563). Here are a few key considerations:

- All thesis proposals are limited in length to the signature coversheet plus 20 or fewer double-spaced, single-sided or double-sided, numbered pages in a font size no smaller than 12 point. Proposals longer than this will not be accepted, however, appendices and references are not included in the 15-page limit, and must be numbered separately, using lower-case Roman numerals. 
- Each chapter must be outlined in the style of a manuscript with a short introduction (including statement of problem and justification for work), clear objectives, and methods that clearly address the objectivs.
- A clear demonstration of knowledge of the literature with appropriate sources is important.




#### PhD Qualifying Exam 

The committee should be provided with the research proposal ahead of time, because this will shape what they decide is important to cover in the qualifying exams. Questions about the proposal are highly appropriate as part of the oral exam. The qualifying exam typically happens at the end of year 2 or the start of year 3. If the qualifying exam has not been completed by the end of year 3, a student may be placed on probation. 


##### Outline of process for qualifying exams (written and oral components):

- The Student schedules dates for the (a) written and (b) oral portions of the exam
 + The written portion does not require committee members’ presence. It should be completed in time for committee members to review answers before the oral, around two weeks in advance.
 + The oral portion requires all members’ participation (in person or via zoom).
 + Use meeting schedulers like when2meet or doodle to identify a two-hour block that works for the oral exam. It is advised you schedule this far in advance, ideally when your committee members have their schedules for the next semester (2-3 months is ideal).
- The Student chooses three areas of specialization in consultation with her committee
 + Discuss and agree in advance whether the exam is open- or closed-book, time limits, and expected length of written answers (usually 2-5 pages each)
 + Committee members each submit 2-3 possible questions  to Easton, who selects and provides them to The Student on the agreed date(s) – often, one question per day within a single week
 + The Student answers selected questions in essay form and returns those answers to Easton
 + Easton circulates all answers to all committee members
- Oral exam: about 2 hours
 + Committee members take turns asking The Student questions (including but not limited to the written exam and research proposal; general knowledge in relevant areas is also appropriate/fair game)
 + The Student leaves the room and the committee decides whether she has earned a pass, conditional pass (needs to re-do some portion of the exam), or fail. 
 + She comes back, we tell her the decision, and go on from there.
 + Once she has passed the exam, The Student fills out paperwork, Easton signs it, and it goes to Lisa Buchalski and thence to the graduate school. This includes nominating her Doctoral Dissertation Committee, which may look a lot like her current Guidance Committee.
- There are two forms
 + [Grad school Doctoral Candidacy form](https://universitysystemnh.sharepoint.com/teams/COLSASocialMedia/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FCOLSASocialMedia%2FShared%20Documents%2FWebsite%2Fdoctoral%2Dcandidacy%2Dform%2Epdf&parent=%2Fteams%2FCOLSASocialMedia%2FShared%20Documents%2FWebsite&p=true&ga=1) (only GPC and advisor sign)
 + [DBS Comprehensive Exam form](https://universitysystemnh.sharepoint.com/:b:/r/teams/UNHDBS/Shared Documents/Graduate Students/DBS Grad Forms/DBS_compexamform.pdf?csf=1&web=1&e=A8S2mN) (all committee members must sign)


##### Advice for qualifying exams

The candidacy/qualifying/comprehensive exam can seem intimidating. It will require you to take at least one month off your typical routine (maybe longer if you need to TA or have other commitments) to prepare. However, as long as you study you will pass. Easton and your committee will not have agreed to you scheduling Comps if they didn’t think you would be ready. 

Scheduling – Ideally, you will pass your Comps before the end of your fifth semester. Work backwards and figure out how much time you will need to schedule both orals and written exams and study. You will need to propose to your committee that you are ready to take Comps, ideally during a committee meeting so that your progress is fresh in their minds and you have a captive audience. Bonus points if you can make everyone take out their calendars during the meeting and schedule the orals then and there! If you need to email your committee instead, account for how long it will take for everyone to 1) agree that you are ready for Comps and 2) agree on a date and time. Ideally, do this 2-4 months in advance. 

Focal areas and Reading list– When planning on your study schedule, you should plan on doing all of your prep work before your writtens, not your orals. You will want to take a breahter/refocus a bit in between your writtens and orals, and having to play catchup is not ideal.

Around 6-8 weeks before your written exam week, write to each committee member to determine 1) what areas of focus they should question you on, and 2) suggested reading lists given these focal areas. Focus areas should be tailored to each committee member’s main disciplines and how they intersect with your work. You can start off with a list you and Easton decide on, and then see what they think. Along with the focal areas, you should solicit a reading list from your committee members. This reading list can be an enormous help in your studying, as the textbooks/review papers/seminal papers they suggest are likely to be different from the reading you’ve been doing for your proposal and individual experiments. They should send you somewhere between 5-15 resources. 

How to study – At least 4-6 weeks before your written exam date, you should have all meetings organized, reading material acquired, and focus areas agreed upon. Organization of your readings and notes is critical and highly personal – use what has worked for you historically. Notetaking programs like Notion and OneNote are highly customizable and use a reference manager to organize your resources (ideally in a separate “comps” folder). If it is helpful to you, calculate how many papers/pages you need to read a day – this will help you break down the intimidating stack of reading! 

Given the time limits you have during your written and oral exams, having a good recall of 1) what a certain paper is about (i.e. Levin and Paine 1974 is about disturbances in intertidal communities...) and 2) what papers you can cite or refer to on a given subject (Metabolic Theory of Ecology originated from  1997 West, Brown, and Enquist paper). They are not going to ask you about methodological details (generally), or a specific result. Instead, you should focus on the major conclusions, theories, patterns, models, trends, etc. That are discussed in each paper. This is why you will find yourself reading more review papers, textbooks, synthesis papers, etc. Than you probably normally do. 

Take notes, ideally both in the text of each paper and in a single document/program so that you can easily refer back to all your notes later. 

My master’s advisor once told me to follow the 6-6-6 rule... start studying six weeks before your exam date, six days a week, six hours a day. I don’t think working six days a week is at all necessary, but this structure can give you a general clue for how much time you should be spending. 














