# Producing quality work {#producing-quality-work}

For better or worse, publications are a key currency in science. They
are one of the main ways we track scientific progress and individual
production. Authorship on papers can be one of the most fraught topics
and is therefore often ignored until the last minute. This is a bad
strategy and only leads to resentment among co-authors. Therefore,
authorship (in terms of composition and order) should be determined at
the onset of the project. The specifics might change throughout the
project, but it is key to have a starting point to work with from the
start. The term “significant scientific contributions” is often used for
defining who should be included as an author. In this lab, we use the
definition from the International Committee of Medical Journal Editors
(<http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html>):
The ICMJE recommends that authorship be based on the following 4
criteria:

-   Substantial contributions to the conception or design of the work;
    or the acquisition, analysis, or interpretation of data for the
    work; AND
-   Drafting the work or revising it critically for important
    intellectual content; AND
-   Final approval of the version to be published; AND
-   Agreement to be accountable for all aspects of the work in ensuring
    that questions related to the accuracy or integrity of any part of
    the work are appropriately investigated and resolved. In addition,
    “the corresponding author is the one individual who takes primary
    responsibility for communication with the journal during the
    manuscript submission, peer review, and publication process”.

Thus, simply providing some data or providing minor comments on a
manuscript do not warrant authorship, but they should still be
acknowledged. Just because I am your advisor, does not mean I warrant
authorship on your publications. The same goes for your committee
members. There will likely be publications that you are involved with
that I have only a small part in. That being said, the most common order
(but by no means the only) for authorship in the lab is Grad Student
Lead, Other Contributors, with the PI as the last author. It is common
for the grad student lead and the PI to both be corresponding authors.

## Advice on writing

Key principles on writing in the lab

- Use active voice 
- Write clearly and concisely
- Avoid filler words, long sentences, and weak verbs

Here are some examples of the last bullet:

- Long sentences 
   - Example: “The connection between sedimentation and flow has been investigated in depth and if cleaning and flow rates are highly correlated this knowledge supports the pressures to maintain frequent cleaning implementations in aquaculture”
- Filler words
   - Example: “The uncertainties lie with how oysters and other bivalves will be influenced by these increased disruptions through the cleaning process." You could write, “The impact of increased cleaning disruptions on oysters and other bivalves is uncertain.”
   - Example: “For further identifying health of oysters, we used gaping behavior as a proxy due to its connection to respiration and feeding.” You could write, “To assess oyster health, we used gaping behavior as a proxy for respiration and feeding.” – this is a subtle shift, but a few less words makes the sense feel so much smoother
- Verb choice ([https://www.aje.com/arc/editing-tip-powerful-verbs/](https://www.aje.com/arc/editing-tip-powerful-verbs/) and [https://www.brandeis.edu/writing-program/resources/faculty/handouts/active-verbs-discussing-ideas.html](https://www.brandeis.edu/writing-program/resources/faculty/handouts/active-verbs-discussing-ideas.html))
   - Example: “…the connection to potential benefits have not been investigated." You could instead write “…the connection to potential benefits remains unexplored." Often verbs that rely on “have”  or “can” (which are helping (auxiliary) verbs) in the sentence indicate weak verbs.
   - Example: “Filter feeders landing on the surrounding cages can lead to declines in food abundances for the bivalves within." You could write, "Filter feeders landing on the surrounding cages can reduce food abundance for bivalves."
   - Example: “Biofouling is an additional factor associated with cleaning implementation and impede flow rates in cages” You could write "Biofouling contributes to cleaning challenges and reduces flow rates in cages."

### Specific pieces of advice

- [How to write about regression outputs](https://doi.org/10.1111/2041-210X.12577)

## Where to publish 

A lot has been written on this topic. In general, we like to publish our work open access (which may be in the form of a preprint) and solid journals. The goal is to publish in the right journal as opposed to the "best journal possible". One useful tip is to go through your list of references. What journals do you cite? That probably gives you a good clue as to the write audience for your work. 

At UNH, we have a special [agreement with Cambridge](https://libraryguides.unh.edu/openaccess/memberships) to publish open access for free, including in the following journals.

- [Environmental Data Science](https://www.cambridge.org/core/journals/environmental-data-science)
- [Oryx](https://www.cambridge.org/core/journals/oryx)
- [Coastal Futures](https://www.cambridge.org/core/journals/cambridge-prisms-coastal-futures/overview-for-authors)
- [Environmental Conservation](https://www.cambridge.org/core/journals/environmental-conservation)

We also publish for free, or cheaply, in [PeerJ](https://peerj.com/). 

## Authorship resources

-   <http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html>
-   <https://www.sciencemag.org/careers/2010/04/conventions-scientific-authorship>
-   <https://www.sciencemag.org/careers/2021/05/how-navigate-authorship-scientific-manuscripts>

### Acknowledgements (example with lots of details)

The authors would like to thank Josie DeMerit and Ella Williams for their assistance completing the laboratory experiments. We conducted data analysis of cardiac activity on the Premise High Performance Computing Cluster, supported by the University System of New Hampshire Research Computing Center and by New Hampshire-INBRE through an Institutional Development Award (IDeA), P20GM103506, from the National Institute of General Medical Sciences of the NIH. Field work and organism collection was completed under New Hampshire Fish and Game Department permit MFD 2430. This research was supported through grants to ARV by the New Hampshire Sea Grant Graduate Fellowship, and UNH School for Marine Science and Ocean Engineering (SMSOE) Graduate Student Fund. Additional funds were awarded by the New Hampshire Agricultural Experiment Station CREATE program through a joint funding program with the USDA National Institute of Food and Agriculture (Hatch award no. 7004018) and the State of New Hampshire. 
